### ISSUE TITLE
Russian language for FDI

### ISSUE THREAD

**Issue by petr-akhlamov** [shidel/FDI#1]
I create russian translation for FDI. I already made translate for KEYBOARD.LST and SETLANG.BAT. Soon i will complete translation for FDSETUP.DEF and publish files here.

**Comment by petr-akhlamov** [comment]
[UTF-8 and CP866 v2.zip](https://github.com/shidel/FDI/files/1372407/UTF-8.and.CP866.v2.zip)

**Comment by shidel** [comment]
Thank you for your Russian language translations. I hope to find the time to incorporate them into FDI sometime soon. However, I have been very busy lately and do not know how soon I will get to them. In the meantime, I have added them to the pending directory to prevent them from being forgotten.

**Comment by petr-akhlamov** [comment]
[UTF-8 and CP866 v3.zip](https://github.com/shidel/FDI/files/1382407/UTF-8.and.CP866.v3.zip)
(CP866 - for using, UTF-8 - for changes by users.)

**Comment by shidel** [comment]
Thank you again for your contribution. The Russian language translations for FDI have now been included and will be available in the upcoming release.
