### ISSUE TITLE
Translate welcome message

### ISSUE THREAD

**Issue by bitigchi** [shidel/FDI#10]
Is it possible to translate the first boot "Welcome to FreeDOS operating system blah blah" message in welcome.bat? It would be a welcome improvement, since it's the first "message" that greets the user.

**Comment by shidel** [comment]
The "**_Welcome to FreeDOS_**" package is dynamically created by the **RBE** _(release build environment)_ during the creation of the OS release media. Language specific versions of the **_welcome message_** are pulled from their respective **FDI** translation file. Those lines start with **AUTO_**_?????_**=** at roughly line [147 ](https://github.com/shidel/fd-nls/blob/2542ff995c622b78a26db1bf56b68bb0dd005e70/fdi/language/tr/FDSETUP.DEF#L147) And that is what would need changed (prerelease) to update that message. 

On the other hand, If you mean to just change the message on your computer? The **welcome.bat** file reads its translations from the **%DOSDIR%\NLS\WELCOME.%LANG%** file. If a Language specific version is not present there, it will fall back to **%DOSDIR%\NLS\WELCOME.EN**. And if that fails, it just outputs some text baked into the **welcome.bat** file. 

I hope that explains what is going on and what needs updated to make changes to that text.

**Comment by bitigchi** [comment]
After I installed RC3, I’ve noticed that it’s translated! Thanks for the reply though, wish I could update this ticket sooner. Sorry!
