### ISSUE TITLE
Automatic Internet configuration in VirtualBox even after installation

### ISSUE THREAD

**Issue by cardpuncher** [shidel/FDI#13]
Again, a feature request from the user's perspective: when using 1.3-RC3 in Live mode with VirtualBox, Internet is automatically configured and simply launching say Links allows the user to browse websites. But after installing FreeDOS and booting from the hard disk, the same Links, or Lynx, return a "NO PACKET DRIVER FOUND." message.

Sure, one could go struggle with the documentation, edit config files and so on, but wouldn't it be better to provide direct Internet connection as with the live mode?

Also, a question: in Live mode, would it be possible to put FDNPKG's config file somewhere in R: and adjust the %FDNPKG.CFG% environment variable accordingly so that we can avoid the "No repository is configured. You need at least one" message when trying to "install" a package from a repo?

**Comment by shidel** [comment]
I assume that you performed only a BASE install. I have considered having FDI automatically include FDNET on supported hardware. However with few exceptions, BASE is a minimal install of the packages needed to replicate the functionality of MS-DOS. Leave it out of BASE or include it. Neither seems to be a perfect answer. I lean towards including it. But, I could say that about several other packages that aren't included. Perhaps bring it up on the mailing list. Maybe Jim and the community will agree (or could be convicted) that it should always get installed on supported hardware. 

In Live mode, FDNPKG should install an remove packages to R:. I need to check and make sure that is happening in the RBE.
