### ISSUE TITLE
lDebug package missing

### ISSUE THREAD

**Issue by ecm-pushbx** [shidel/FDI#14]
Is this the right place to suggest a package be included?

Jim [uploaded to ibiblio my release](http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/dos/debug/ldebug/) originating in 2021 February. More information about this application is [available on my website](https://ulukai.org/ecm/web/#projects-ldebug) and linked from there.

From the recent freedos-devel mailing list discussion I found [this report](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc4/report.html) and noticed that it doesn't include lDebug yet. It would probably fit the devel category best. (It is an advanced fork of FreeDOS Debug.)

**Comment by shidel** [comment]
_(Much of this does not apply to you or your program. I get this question in one form or another often enough, I think I'm going to use most of this reply here to create a "boiler-plate" response. That way I don't need to type out variations of it anymore. :-) )_

Here is fine. But generally, such discussions happen mostly on the mailing list.

If I recall correctly, there was more than one version. From the messages to the mailing list, I was under the impression it was a **"work in progress"** and not yet ready to be added to the [Online Repository](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/latest/pkg-html/index.html). 

Files mirrored on [ibiblio](http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/) have little to do with contents of the Online Repository. And, the reverse is also true. Something can be mirrored but not present in the Repo and something can be in the Repo and not directly mirrored. 

However, if something is not in the Repo it will not be on a release. Most of the packages in the Repo are provided in some form _(installed or just included on the Bonus CD)_. But, not all. For inclusion to the Repo, the software must be open source with source included _(which yours is)_. Programs that are source only require a lot of extra work to be included. So, source only is rarely added. In addition, having the program in a **"ready-to-go"** compatible package _(not just a zip)_ which helps a lot _(which yours is)_.

Even if all of those conditions are satisfied, inclusion on the Repo is not guaranteed. For example, having an additional DOOM clone is not really desired. We already have two.

Once a package is in the Online Repo, a decision on type of inclusion or exclusion from the release is made. Generally, most packages on the Repo make onto the release media in some form. 

With a few adjustments to the LSM metadata, I have added the package for [lDebug](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/repositories/latest/pkg-html/ldebug.html) to the Online Repository and will mention it for inclusion the next time that subject is discussed.

I suggest also posting to the mailing list recommending it's inclusion. 

Thank you,

Jerome

**Comment by ecm-pushbx** [comment]
Thanks for the reply!

> If I recall correctly, there was more than one version. From the messages to the mailing list, I was under the impression it was a "work in progress" and not yet ready to be added to the Online Repository.

There were several drafts while we figured out what to include and in what layout for the FreeDOS package. However, the ldebug1.zip now found in the FreeDOS package subdirectory, and mirrored to ibiblio, is the final released package. The actual application and documentation other than fdbuild.txt and the LSM are all as in their original state from the 2021-02-15 release.

You already mentioned that my package is free. However, it can also be built with a (nontrivial, crosscompiling) free toolchain. FreeDOS Debug since 1.14 only builds with MASM or the Open Watcom based JWASM, the latter which is technically "open source" but not accepted as free software by everyone. 

> I suggest also posting to the mailing list recommending it's inclusion.

I will send a mail later today. You do mean the freedos-devel list, right?

**Comment by shidel** [comment]
> Thanks for the reply!

Your welcome.  

> I will send a mail later today. You do mean the freedos-devel list, right?

Yup. Maybe freedos-users as well. 

Won't hurt to remind everyone it exists and could be added to the release. :-)

**Comment by ecm-pushbx** [comment]
Sent the mail! Bit later than I thought because I took the opportunity to push out a new release.

Also I compared your updated LSM with mine. Perhaps http://wiki.freedos.org/wiki/index.php/LSM should be updated to include the "Summary" and "Group" fields? This documentation is what I based the LSM I provided on.

**Comment by shidel** [comment]
The LSM on the wiki is fine. But, its been around along time. There are a couple additions the online repo and  other programs can use. Since, the Description field should be fairly short and concise, a Summary field get used for much longer information. Group field isn't needed or really used by anything. A Modified-date field that is more or less handled by the repository automatically and eventually will aid in cross-repo syncing. And also a Changes field that is used in an the repo's RSS feed and displayed on the HTML pages as "Whats New". All these additional fields are completely optional.
