### ISSUE TITLE
Add to installer two russian keymaps - typewriter and dos

### ISSUE THREAD

**Issue by petr-akhlamov** [shidel/FDI#2]
Here i was published russian keymaps - http://sourceforge.net/p/freedos/bugs/174/
Please, update list of keymaps (needed to update russian, add russian dos and russian typewriter)

**Comment by shidel** [comment]
Hello. I am sorry about having such a long delay in a replying to your request. I had reached out to the developer of the [mkeyb](http://www.drivesnapshot.de/freedos/mkeyb.htm) program about your needs and was waiting (and hoping) he would integrate your additional Russian keyboard maps. Unfortunately, it appears he has not included them. Without having one of the keyboard map programs (mkeyb, keyb, etc) supporting those keyboards, I will be unable to add them as options to the installer.  Perhaps if you reach out directly to the developers of those programs, you may have better luck in getting their cooperation. Once one of the drivers support those keymaps, I would be pleased to add them as options in the installer.
