### ISSUE TITLE
Typo in Intro

### ISSUE THREAD

**Issue by Ergonomicmike** [shidel/FDI#4]
"However, the entire process can be ported without to much difficulty ..."

should be

"can be ported without too much difficulty ..."

**Comment by shidel** [comment]
Thanks, I corrected it. Unfortunately, I'll have to rewrite a bunch of stuff in the wiki for FreeDOS 1.3. The entire release build process is changing. Overall, I think the new process is superior and will be easier for others to create custom releases.
