### ISSUE TITLE
is bugreporting allowed in this repo?

### ISSUE THREAD

**Issue by TAbdiukov** [shidel/FDI#5]
As far as I know, the FreeDos code is dealt  with on sourceforge's svn. But it appears that now this repo is mentioned on the freedos website. If I notice a bug in Freedos, may I report it here?

Cheers

**Comment by shidel** [comment]
Hi. Every FreeDOS release is comprised of many programs, utilities and drivers that are created and (hopefully) maintained by many different people and may not be directly affiliated with The FreeDOS project. It is best to post a bug report in an appropriate place. 
Mostly, this Repo is for the Official FreeDOS installer and it’s media. If you are experiencing a bug with the installer, this is definitely the correct place to post it.
However, other issues should go to their respective repos or to the main repo on sourceforge at https://sourceforge.net/p/freedos/bugs/ 
I hope this was helpful.
