### ISSUE TITLE
Installer bug in freedos 1.3RC2

### ISSUE THREAD

**Issue by dandelionred** [shidel/FDI#7]
When scrolling through the "What is your preferred language?" list I noticed the Dutch option is buggy

Scroll to Esperanto:
<img src="https://user-images.githubusercontent.com/19490344/77698294-0ca51600-6fb9-11ea-8fa4-21e77258e109.png" width="400">

Now scroll one step down (should be Dutch) and notice it says Esperanto again.
<img src="https://user-images.githubusercontent.com/19490344/77698303-0e6ed980-6fb9-11ea-9197-f41596cfe262.png" width="400">

It is because of line 18 in `FREEDOS/SETUP/NL/FDSETUP.DEF` on the install media. Notice below Esperanto comes after Dutch. While in all other `FREEDOS/SETUP/*/FDSETUP.DEF` files their positions are swapped.
```
LANG_LIST=/r4/c32 'Engels' /e/p/r4/c32 'Spaans' /e/p/r4/c32 'Frans' /e/p/r4/c32 'Duits' /e/p/r4/c32 'Nederlands' /e/p/r4/c32 'Esperanto' /e/p/r4/c32 'Turks' /e/p/r4/c32 'Russisch' /e
```

I tried swapping the things on the istall media and it fixed the problem.

Also in `FREEDOS/SETUP/NL/FDSETUP.DEF` the following lines have Esperanto and Dutch swapped (compared to all other language defs). In case `LANG_LIST` above is automaticly generated from these lines it might be the problem's source.
```
LANG_EN=Engels
LANG_ES=Spaans
LANG_FR=Frans
LANG_DE=Duits
LANG_NL=Nederlands  <===== these lines should
LANG_EO=Esperanto  <===== be swapped
LANG_TR=Turks
LANG_RU=Russisch
```

**Comment by shidel** [comment]
Thanks, changed order in sources.
