### ISSUE TITLE
Bug in 1.3RC2 installer when picking Russian language

### ISSUE THREAD

**Issue by dandelionred** [shidel/FDI#8]
Reproduce steps below

Pick installer language=Russian
<img src="https://user-images.githubusercontent.com/19490344/77703696-213adb80-6fc4-11ea-988b-0dab1bfc3c9f.png" width="400">

Pick "Continue installation"
<img src="https://user-images.githubusercontent.com/19490344/77703735-3283e800-6fc4-11ea-80c0-76a7ea59381e.png" width="400">

Pick layout=Russian
<img src="https://user-images.githubusercontent.com/19490344/77703756-3dd71380-6fc4-11ea-9b53-fdb0ea9dd1f9.png" width="400">

**======== Bug1**: The next screen looks like this, just an empty rectangle. I pressed Enter here
<img src="https://user-images.githubusercontent.com/19490344/77703855-737bfc80-6fc4-11ea-961d-6eac7504614c.png" width="400">

Now finish the installation and reboot.

**======== Bug2**: Notice the garbage instead of localized text in Russian.
<img src="https://user-images.githubusercontent.com/19490344/77704192-35330d00-6fc5-11ea-940d-e66ec2354e4a.png" width="400">

**======== Bug3**: Keyboard layout is messed. For example "m" is mapped into comma (I tried all keys to find "m" to no avail btw). It is because of `mkeyb FR` (!) in `fdauto.bat`. I commented it out and the layout was back to latin after reboot.

After all, I've made such changes to fdauto.bat
```patch
@@ -27,12 +27,13 @@
 IF NOT EXIST %DOSDIR%\CPI\EGA3.CPX GOTO NoCodePage
 LH DISPLAY CON=(EGA,,1)
 MODE CON CP PREP=((866) %DOSDIR%\CPI\EGA3.CPX)
-LH MODE CON CP SEL=866
+MODE CON CP SEL=866
+MODE CON CP REFRESH
 REM LH KEYB RU,,keybrd3.sys
 REM LH CHCP 866
 :NoCodePage
 
-mkeyb FR
+rem mkeyb FR
 
 REM MOUSE
 CTMOUSE
```

After reboot the localization works correctly like this.
<img src="https://user-images.githubusercontent.com/19490344/77705696-061e9a80-6fc9-11ea-9167-7d2e361dadbe.png" width="400">

**Comment by shidel** [comment]
Sorry, I didn't reply to you sooner. I've been very busy working on numerous aspects of the installer. 

Thanks to your feedback and detailed information, I think I have resolved all the issues you described for the upcoming 1.3-RC3 release. Your bug report was instrumental in that process.

Once again, thank you.
